import { asCardId, type FormatBundle } from "@cardengine/engine";

export const MTG_FORMATS: Record<string, FormatBundle> = {
  standard: {
    id: "standard",
    game: "mtg",
    name: "Standard",
    updatedAt: "2026-01-01T00:00:00Z",
    rules: {
      minMain: 60,
      maxSide: 15,
      maxCopiesPerCard: 4,
      bannedCardIds: [
        asCardId("Oko, Thief of Crowns"),
        asCardId("Omnath, Locus of Creation"),
      ],
      rotation: {
        legalSetIds: ["dmu","bro","one","mom","woe","lci","mkm","otj","blb","dsk","fdn"],
      },
    },
  },
  modern: {
    id: "modern",
    game: "mtg",
    name: "Modern",
    updatedAt: "2026-01-01T00:00:00Z",
    rules: {
      minMain: 60,
      maxSide: 15,
      maxCopiesPerCard: 4,
      bannedCardIds: [
        asCardId("Blazing Shoal"), asCardId("Chrome Mox"), asCardId("Dark Depths"),
        asCardId("Deathrite Shaman"), asCardId("Eye of Ugin"), asCardId("Gitaxian Probe"),
        asCardId("Green Sun's Zenith"), asCardId("Hogaak, Arisen Necropolis"),
        asCardId("Hypergenesis"), asCardId("Mental Misstep"), asCardId("Oko, Thief of Crowns"),
        asCardId("Once Upon a Time"), asCardId("Ponder"), asCardId("Preordain"),
        asCardId("Punishing Fire"), asCardId("Rite of Flame"), asCardId("Sensei's Divining Top"),
        asCardId("Simian Spirit Guide"), asCardId("Skullclamp"), asCardId("Splinter Twin"),
        asCardId("Summer Bloom"), asCardId("Tibalt's Trickery"), asCardId("Treasure Cruise"),
        asCardId("Umezawa's Jitte"), asCardId("Uro, Titan of Nature's Wrath"),
      ],
    },
  },
  pioneer: {
    id: "pioneer",
    game: "mtg",
    name: "Pioneer",
    updatedAt: "2026-01-01T00:00:00Z",
    rules: {
      minMain: 60,
      maxSide: 15,
      maxCopiesPerCard: 4,
      bannedCardIds: [
        asCardId("Balustrade Spy"), asCardId("Bloodstained Mire"), asCardId("Felidar Guardian"),
        asCardId("Flooded Strand"), asCardId("Inverter of Truth"), asCardId("Kethis, the Hidden Hand"),
        asCardId("Leyline of Abundance"), asCardId("Lurrus of the Dream-Den"),
        asCardId("Nexus of Fate"), asCardId("Oko, Thief of Crowns"), asCardId("Once Upon a Time"),
        asCardId("Polluted Delta"), asCardId("Smuggler's Copter"), asCardId("Undercity Informer"),
        asCardId("Uro, Titan of Nature's Wrath"), asCardId("Veil of Summer"),
        asCardId("Walking Ballista"), asCardId("Wilderness Reclamation"),
        asCardId("Windswept Heath"), asCardId("Wooded Foothills"),
      ],
    },
  },
  legacy: {
    id: "legacy",
    game: "mtg",
    name: "Legacy",
    updatedAt: "2026-01-01T00:00:00Z",
    rules: {
      minMain: 60,
      maxSide: 15,
      maxCopiesPerCard: 4,
      bannedCardIds: [
        asCardId("Ancestral Recall"), asCardId("Balance"), asCardId("Black Lotus"),
        asCardId("Channel"), asCardId("Demonic Consultation"), asCardId("Demonic Tutor"),
        asCardId("Fastbond"), asCardId("Flash"), asCardId("Gitaxian Probe"),
        asCardId("Mox Emerald"), asCardId("Mox Jet"), asCardId("Mox Pearl"),
        asCardId("Mox Ruby"), asCardId("Mox Sapphire"), asCardId("Necropotence"),
        asCardId("Oko, Thief of Crowns"), asCardId("Skullclamp"), asCardId("Sol Ring"),
        asCardId("Time Vault"), asCardId("Time Walk"), asCardId("Timetwister"),
        asCardId("Tinker"), asCardId("Tolarian Academy"), asCardId("Treasure Cruise"),
        asCardId("Yawgmoth's Will"),
      ],
    },
  },
  vintage: {
    id: "vintage",
    game: "mtg",
    name: "Vintage",
    updatedAt: "2026-01-01T00:00:00Z",
    rules: {
      minMain: 60,
      maxSide: 15,
      maxCopiesPerCard: 4,
      restrictedCardIds: [
        asCardId("Ancestral Recall"), asCardId("Black Lotus"), asCardId("Brainstorm"),
        asCardId("Channel"), asCardId("Demonic Tutor"), asCardId("Dig Through Time"),
        asCardId("Flash"), asCardId("Gitaxian Probe"), asCardId("Gush"),
        asCardId("Imperial Seal"), asCardId("Mox Emerald"), asCardId("Mox Jet"),
        asCardId("Mox Pearl"), asCardId("Mox Ruby"), asCardId("Mox Sapphire"),
        asCardId("Mystical Tutor"), asCardId("Necropotence"), asCardId("Sol Ring"),
        asCardId("Time Vault"), asCardId("Time Walk"), asCardId("Timetwister"),
        asCardId("Tinker"), asCardId("Tolarian Academy"), asCardId("Treasure Cruise"),
        asCardId("Vampiric Tutor"), asCardId("Yawgmoth's Will"),
      ],
    },
  },
  commander: {
    id: "commander",
    game: "mtg",
    name: "Commander",
    updatedAt: "2026-01-01T00:00:00Z",
    rules: {
      exactMain: 100,
      maxCopiesPerCard: 1,
      bannedCardIds: [
        asCardId("Ancestral Recall"), asCardId("Balance"), asCardId("Biorhythm"),
        asCardId("Black Lotus"), asCardId("Braids, Cabal Minion"), asCardId("Channel"),
        asCardId("Coalition Victory"), asCardId("Emrakul, the Aeons Torn"),
        asCardId("Erayo, Soratami Ascendant"), asCardId("Fastbond"), asCardId("Flash"),
        asCardId("Gifts Ungiven"), asCardId("Golos, Tireless Pilgrim"), asCardId("Griselbrand"),
        asCardId("Hullbreacher"), asCardId("Iona, Shield of Emeria"), asCardId("Karakas"),
        asCardId("Leovold, Emissary of Trest"), asCardId("Library of Alexandria"),
        asCardId("Limited Resources"), asCardId("Lutri, the Spellchaser"),
        asCardId("Mox Emerald"), asCardId("Mox Jet"), asCardId("Mox Pearl"),
        asCardId("Mox Ruby"), asCardId("Mox Sapphire"), asCardId("Panoptic Mirror"),
        asCardId("Paradox Engine"), asCardId("Primeval Titan"), asCardId("Prophet of Kruphix"),
        asCardId("Recurring Nightmare"), asCardId("Rofellos, Llanowar Emissary"),
        asCardId("Sundering Titan"), asCardId("Sway of the Stars"), asCardId("Sylvan Primordial"),
        asCardId("Time Vault"), asCardId("Time Walk"), asCardId("Tinker"),
        asCardId("Tolarian Academy"), asCardId("Trade Secrets"), asCardId("Upheaval"),
        asCardId("Worldfire"), asCardId("Yawgmoth's Bargain"),
      ],
      special: { commanderIdentity: true, requireCommander: true },
    },
  },
  pauper: {
    id: "pauper",
    game: "mtg",
    name: "Pauper",
    updatedAt: "2026-01-01T00:00:00Z",
    rules: {
      minMain: 60,
      maxSide: 15,
      maxCopiesPerCard: 4,
      bannedCardIds: [
        asCardId("Arcum's Astrolabe"), asCardId("Atog"), asCardId("Bonder's Ornament"),
        asCardId("Chatterstorm"), asCardId("Cloud of Faeries"), asCardId("Cranial Plating"),
        asCardId("Daze"), asCardId("Empty the Warrens"), asCardId("Fall from Favor"),
        asCardId("Frantic Search"), asCardId("Galvanic Relay"), asCardId("Gitaxian Probe"),
        asCardId("Grapeshot"), asCardId("Gush"), asCardId("High Tide"),
        asCardId("Hymn to Tourach"), asCardId("Invigorate"), asCardId("Monastery Swiftspear"),
        asCardId("Mystic Sanctuary"), asCardId("Peregrine Drake"), asCardId("Prophetic Prism"),
        asCardId("Sinkhole"), asCardId("Temporal Fissure"), asCardId("Treasure Cruise"),
      ],
      special: { commonOnly: true },
    },
  },
};
